image:
  name: node:18-alpine

variables:
  CI_PROJECT_NAME: youdescribex-app

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build-stage:
  stage: build
  tags:
    - frontend
    - staging

  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: always

  script:
    - echo "Building YouDescribe Frontend in staging"
    - echo "PORT $PORT"
    - echo "REACT_APP_LOGROCKET_ID $REACT_APP_LOGROCKET_ID"
    - echo "REACT_APP_YDX_BACKEND_URL=$REACT_APP_YDX_BACKEND_URL"
    - docker build
      --build-arg REACT_APP_LOGROCKET_ID=$REACT_APP_LOGROCKET_ID
      --build-arg REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
      --build-arg REACT_APP_REDIRECT_URL=$REACT_APP_REDIRECT_URL
      --build-arg REACT_APP_YOUTUBE_API_URL=$REACT_APP_YOUTUBE_API_URL
      --build-arg REACT_APP_YOUTUBE_API_KEY=$REACT_APP_YOUTUBE_API_KEY
      --build-arg REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID
      --build-arg REACT_APP_USE_YDX=$REACT_APP_USE_YDX
      --build-arg REACT_APP_YDX_BACKEND_URL=$REACT_APP_YDX_BACKEND_URL
      --build-arg REACT_APP_CLASSIC_BACKEND_URL=$REACT_APP_CLASSIC_BACKEND_URL
      --build-arg REACT_APP_CLASSIC_BACKEND_URL_VERSION=$REACT_APP_CLASSIC_BACKEND_URL_VERSION
      --build-arg PORT=$PORT
      --build-arg APP_PORT=$PORT
      -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-1.${CI_PIPELINE_ID}" .
    - echo "Build complete"

build-prod:
  stage: build
  tags:
    - frontend
    - prod

  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always

  script:
    - echo "Building YouDescribe Frontend in prod"
    - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-1.${CI_PIPELINE_ID}" .
    - echo "Build completed"

deploy-stage:
  stage: deploy
  tags:
    - frontend
    - staging

  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: on_success

  script:
    - echo "Stopping old YouDescribe Frontend instance"
    # - docker compose down
    # - echo "Deleting old YouDescribe Frontend container"
    # - echo "Starting up/Deploying newest YouDescribe Frontend build"
    # - docker compose up -d
    - docker run -d -p 0.0.0.0:$PORT:$PORT ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-1.${CI_PIPELINE_ID}
    - echo "Finished deploying YouDescribe Frontend build to staging"

deploy-prod:
  stage: deploy
  tags:
    - frontend
    - prod

  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success

  script:
    - echo "Stopping old YouDescribe Frontend instance"
    - docker compose down
    - echo "Deleting old YouDescribe Frontend container"
    - echo "Starting up/Deploying newest YouDescribe Frontend build"
    - docker compose up -d
    - echo "Finished deploying YouDescribe Frontend build to staging"
