variables:
  CI_PROJECT_NAME: youdescribex-app
  DOCKER_REGISTRY: youdescribe
  S3_BUCKET: youdescribexci
  S3_PATH: youdescribex-app
  CI_REGISTRY: docker.io
  DOCKER_IMAGE_TAG: "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}.${CI_PIPELINE_ID}"

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build-stage:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  tags:
    - frontend
    - dev
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: always
  script:
    - echo "Building YouDescribeX App in staging"
    - docker build -t "${DOCKER_IMAGE_TAG}" .
    - docker push "${DOCKER_IMAGE_TAG}"
    - echo "Build complete"

build-prod:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  tags:
    - frontend
    - prod
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
  script:
    - echo "Building YouDescribeX App in prod"
    - docker build -t "${DOCKER_IMAGE_TAG}" .
    - docker push "${DOCKER_IMAGE_TAG}"
    - echo "Build completed"

deploy-stage:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  tags:
    - frontend
    - dev
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: on_success
  script:
    - echo "Deploying YouDescribeX App build to staging"
    - docker compose down
    - docker compose up -d
    - echo "Deployment to staging completed"

deploy-prod:
  stage: deploy
  tags:
    - frontend
    - prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
  script:
    - echo "Deploying YouDescribeX App build to production"
    - docker compose down
    - docker compose up -d
    - echo "Deployment to production completed"
