stages:
  - build
  - deploy_dev
  - deploy_prod

variables:
  IMAGE_NAME: "${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}.${CI_PIPELINE_ID}"
  CI_PROJECT_NAME: youdescribex-app
  DOCKER_REGISTRY: youdescribe
  CI_REGISTRY: docker.io
  TAR_FILE_NAME: "youdescribex-app.tar"
  TAR_FILE_FOLDER: ".docker"
  TAR_FILE_PATH: "/"

services:
  - docker:24.0.5-dind

before_script:
  - echo "Logging into Docker..."
  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker info

build_dev:
  stage: build
  script:
    - echo "Building Docker image for development..."
    - docker build --build-arg REACT_APP_LOGROCKET_ID="$REACT_APP_LOGROCKET_ID" --build-arg REACT_APP_ENVIRONMENT="$REACT_APP_ENVIRONMENT" --build-arg REACT_APP_REDIRECT_URL="$REACT_APP_REDIRECT_URL" --build-arg REACT_APP_YOUTUBE_API_URL="$REACT_APP_YOUTUBE_API_URL" --build-arg REACT_APP_YOUTUBE_API_KEY="$REACT_APP_YOUTUBE_API_KEY" --build-arg REACT_APP_GOOGLE_CLIENT_ID="$REACT_APP_GOOGLE_CLIENT_ID" --build-arg REACT_APP_USE_YDX="$REACT_APP_USE_YDX" --build-arg REACT_APP_YDX_BACKEND_URL="$REACT_APP_YDX_BACKEND_URL" --build-arg REACT_APP_CLASSIC_BACKEND_URL="$REACT_APP_CLASSIC_BACKEND_URL" --build-arg REACT_APP_CLASSIC_BACKEND_URL_VERSION="$REACT_APP_CLASSIC_BACKEND_URL_VERSION" --build-arg PORT="$PORT" --build-arg APP_PORT="$PORT" -t "${IMAGE_NAME}" .
    - docker push "${IMAGE_NAME}"
    - echo "Build complete"
  tags:
    - frontend
    - dev
  only:
    - dev

build_prod:
  stage: build
  script:
    - echo "Building Docker image for production..."
    - docker build --build-arg REACT_APP_LOGROCKET_ID="$REACT_APP_LOGROCKET_ID" --build-arg REACT_APP_ENVIRONMENT="$REACT_APP_ENVIRONMENT" --build-arg REACT_APP_REDIRECT_URL="$REACT_APP_REDIRECT_URL" --build-arg REACT_APP_YOUTUBE_API_URL="$REACT_APP_YOUTUBE_API_URL" --build-arg REACT_APP_YOUTUBE_API_KEY="$REACT_APP_YOUTUBE_API_KEY" --build-arg REACT_APP_GOOGLE_CLIENT_ID="$REACT_APP_GOOGLE_CLIENT_ID" --build-arg REACT_APP_USE_YDX="$REACT_APP_USE_YDX" --build-arg REACT_APP_YDX_BACKEND_URL="$REACT_APP_YDX_BACKEND_URL" --build-arg REACT_APP_CLASSIC_BACKEND_URL="$REACT_APP_CLASSIC_BACKEND_URL" --build-arg REACT_APP_CLASSIC_BACKEND_URL_VERSION="$REACT_APP_CLASSIC_BACKEND_URL_VERSION" --build-arg PORT="$PORT" --build-arg APP_PORT="$PORT" -t "${IMAGE_NAME}" .
    - docker push "${IMAGE_NAME}"
    - echo "Build complete"
  tags:
    - frontend
    - prod
  only:
    - main

deploy_dev:
  stage: deploy_dev
  script:
    - echo "Deploying to development environment..."
    - docker pull "${IMAGE_NAME}"
    - docker run -d -p $PORT:$PORT --env-file .env "${IMAGE_NAME}"
    - echo "Deployment to development environment completed."
  tags:
    - frontend
    - dev
  only:
    - dev

deploy_prod:
  stage: deploy_prod
  script:
    - echo "Deploying to production environment..."
    - docker pull "${IMAGE_NAME}"
    - docker run -d -p $PORT:$PORT --env-file .env "${IMAGE_NAME}"
    - echo "Deployment to production environment completed."
  tags:
    - frontend
    - prod
  only:
    - main