version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youdescribe-frontend
    ports:
      - ${PORT}:${PORT}
    restart: always
    environment:
      - REACT_APP_LOGROCKET_ID=$REACT_APP_LOGROCKET_ID
      - REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
      - REACT_APP_REDIRECT_URL=$REACT_APP_REDIRECT_URL
      - REACT_APP_YOUTUBE_API_URL=$REACT_APP_YOUTUBE_API_URL
      - REACT_APP_YOUTUBE_API_KEY=$REACT_APP_YOUTUBE_API_KEY
      - REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID
      - REACT_APP_USE_YDX=$REACT_APP_USE_YDX
      - REACT_APP_YDX_BACKEND_URL=$REACT_APP_YDX_BACKEND_URL
      - REACT_APP_CLASSIC_BACKEND_URL=$REACT_APP_CLASSIC_BACKEND_URL
      - REACT_APP_CLASSIC_BACKEND_URL_VERSION=$REACT_APP_CLASSIC_BACKEND_URL_VERSION
      - PORT=$PORT