# Use the official Node.js image with the latest version
FROM node:latest

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build arguments for environment-specific variables
ARG REACT_APP_REDIRECT_URL
ARG REACT_APP_YDX_BACKEND_URL
ARG REACT_APP_YOUTUBE_API_URL
ARG REACT_APP_YOUTUBE_API_KEY
ARG REACT_APP_LOGROCKET_ID
ARG REACT_APP_GOOGLE_CLIENT_ID
ARG REACT_APP_USE_YDX
ARG REACT_APP_CLASSIC_BACKEND_URL
ARG REACT_APP_CLASSIC_BACKEND_URL_VERSION
ARG REACT_APP_ENVIRONMENT

# Set environment variables
ENV REACT_APP_REDIRECT_URL=$REACT_APP_REDIRECT_URL
ENV REACT_APP_YDX_BACKEND_URL=$REACT_APP_YDX_BACKEND_URL
ENV REACT_APP_YOUTUBE_API_URL=$REACT_APP_YOUTUBE_API_URL
ENV REACT_APP_YOUTUBE_API_KEY=$REACT_APP_YOUTUBE_API_KEY
ENV REACT_APP_LOGROCKET_ID=$REACT_APP_LOGROCKET_ID
ENV REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID
ENV REACT_APP_USE_YDX=$REACT_APP_USE_YDX
ENV REACT_APP_CLASSIC_BACKEND_URL=$REACT_APP_CLASSIC_BACKEND_URL
ENV REACT_APP_CLASSIC_BACKEND_URL_VERSION=$REACT_APP_CLASSIC_BACKEND_URL_VERSION
ENV REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT

# Build the application
RUN npm run build

# Expose the application port
EXPOSE $PORT

# Start the application
CMD [ "node", "server.js"]