version: '3'

services:
  frontend:
    container_name: youdescribex-frontend
    image: '${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${IMAGE_TAG:-latest}'
    ports:
      - '${PORT}:${PORT}'
    restart: always
    volumes:
      - /mnt/ebs:/mnt/ebs
    environment:
      - REACT_APP_LOGROCKET_ID=${REACT_APP_LOGROCKET_ID}
      - REACT_APP_ENVIRONMENT=${REACT_APP_ENVIRONMENT}
      - REACT_APP_REDIRECT_URL=${REACT_APP_REDIRECT_URL}
      - REACT_APP_YOUTUBE_API_URL=${REACT_APP_YOUTUBE_API_URL}
      - REACT_APP_YOUTUBE_API_KEY=${REACT_APP_YOUTUBE_API_KEY}
      - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
      - REACT_APP_USE_YDX=${REACT_APP_USE_YDX}
      - REACT_APP_YDX_BACKEND_URL=${REACT_APP_YDX_BACKEND_URL}
      - REACT_APP_CLASSIC_BACKEND_URL=${REACT_APP_CLASSIC_BACKEND_URL}
      - REACT_APP_CLASSIC_BACKEND_URL_VERSION=${REACT_APP_CLASSIC_BACKEND_URL_VERSION}
      - PORT=${PORT}
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
